export const testdata = {
  validUser: {
    password: "port80"
  },

  urls: {
    urlForDev: "https://shopify.naturemadedev.com/",
    // loginPage: "/login"
  },

  homePage:{
    bannerName:"A delightful way to take care",
  },

  loginPage:{
    loginTitle:"Login",
    signInTitle:"Sign in"
  },

  search: {
    searchProduct1: "Vitamin B1 100 mg Tablets",
    searchProduct2: "Vitamin B6 100 mg Tablets",
    searchProduct3: "Vitamin D3 1000 IU (25 mcg) Softgels",
    searchProduct4: "Vitamin C Extra Strength 1000 mg Tablets",
    extraStrengthBiotin: "Extra Strength Biotin 2500 mcg Softgels",
    searchProduct5: "Vitamin C + Rose Hips",
    biotinsearchProduct1: "3000 mcg Biotin Gummies for Hair, Skin & Nails",
    biotinsearchProduct2: "Biotin Maximum Strength‡ 5000 mcg Softgels"
  },

  titles: {
    bannername: "Self-care made easy",
    getstart: "GET STARTED",
    shopnow: "EXPLORE GUMMIES",
    shopnowbestsellers: "SHOP BESTSELLERS",
    shopguthealth: "EXPLORE GUMMIES",
    shopGummies: "EXPLORE GUMMIES",
    rejectall: "Reject All",
    acceptall: "Accept All",
    b12: "B12",
    supportpatients: "Providing your patients with science-backed solutions",
    privacyheading: "CATEGORIES OF PERSONAL INFORMATION COLLECTED",
    termsofserviceheading: "Terms of service/use",
    yourPrivacyChoices: "Your Choices Regarding Cookies",
    logintitle: "Login",
    newAccHeading: "Welcome Back",
    whereToBuyheaderTxt: "WHERE TO BUY",
    accountcreation: "Create account",
    wheretobuyTxt: "Where to Buy",
    yourcart: "Your Cart",
    yourCartpage: "Your cart",
    continueshopping: "Continue Shopping",
    yourCartisEmpty: "Your cart is empty",
    prebiotics: "Probiotics",
    createAnAccToFav: "Create an account to see your favorites",
    twopack: "2-Pack",
    freesgiftmsg: "You have earned a Free Gift",
    privacypolicy: "Privacy policy",
    privacyPolicy: "PRIVACY POLICY",
    generalwellness: "GENERAL WELLNESS",
    women: "WOMEN",
    men: "MEN"
  },

  paymentPageDetails: {
    visaCardTxt: "Visa",
    masterCardTxt: "Mastercard",
    amexTxt: "American Express",
    discoverTxt: "Discover",
    andMoreTxt: "and more…",
    creditbutton: "+4",

    visaCardNumber: "4242424242424242",
    masterCardNumbr: "5555555555554444",
    amexCardNumbr: "378282246310005",
    discoverCardNumbr: "6011111111111117",

    cardName: "visa",
    mastercrdName: "Master",
    amexCardName: "American Express",
    discoverCardName: "Discover",

    expiryDate: "02/30",
    expiryDate1: "05/25",

    securityCode: "123",
    amexSecurityCode: "1234",

    thankYouTxt: "Thank you, test!",

    cardnumbrFldErrorMsg: "Enter a valid card number",
    cardnumbermsg: "Enter a card number",
    firstNameErrorMsg: "Enter a first name"
  },

  information: {
    couponcode: "Welcome25"
  },

  informationpage: {
    contctInfrmtionnHeading: "Contact",
    email: "test@maildrop.cc",
    firstName: "test",
    lastName: "user",
    address1: "102 Hickory St",
    city: "Athens",
    zipCode: "35613",
    shippingMethod: "Shipping method",
    Payment: "Payment",
    country: "United States",
    creditcard: "Credit card",
    shippingvalue1: "40.98",
    startNowCode: "STARTNOW1",
    emailerrormessage: "Enter a valid email",
    firstnameerrormessage: "Enter a first name",
    lastnameerrormessage: "Enter a last name",
    addresserrormessage: "Enter an address",
    cityerrormessage: "Enter a city",
    zipcodeerrormsg: "Enter a ZIP / postal code",
    randomZipcode: "12345765432",
    zipcodeRandomAddress: "Enter a valid ZIP code for Texas. Did you mean 75232?",
    subscriptionpolicy: "Subscription Policy",
    isaddresscorrect: "Is the shipping address correct?",
    confirmationmsg: "If yes, proceed to submit the form.",
    shippingaddress: "1917 sedona ln, Dallas TX 75232, United States",
    freeshippingmessage: "FREE",
    claimgiftmsg: "Free",
    eightdollarshippingprice: "$8.00",
    calcutedatstep: "Calculated at next step",
    billingAdressHeadingTxt: "Billing address",
    paymentbutton: "Pay now",
    returntoshipping: "Return to shipping",
    returntocart: "Return to cart",
    returntoinformation: "Return to information",
    continuetoshipping: "CONTINUE TO SHIPPING",
    totalvalue: "$27.99",
    discountcode: "welcome10",
    shippingAddrssGuidPgHeading: "Shipping Address Guide For APO/DPO/FPO",
    privacypolicytext: "Privacy policy",
    refundpolicy: "Refund policy",
    termsofusetext: "Terms of service",
    cancellationpolicy: "Cancellation policy",
    discountcode1: "25off",
    bundleitem: "BUNDLE ITEM (-$16.13)",
    coQ10Softgels: "1 × CoQ10 100 mg Softgels",
    cholestoffSoftgels: "1 × CholestOff Plus® Softgels",
    ultraOmegaSoftgels: "1 × Ultra Omega-3†† from Fish Oil 1400 mg Softgels, Burp-Less♦",
    state: "Alabama",
    discountValidationMsg: "Discount codes cannot be used on orders with bundles. To apply a discount code, click here to remove bundles from your cart"
  },

  headers: {
    atoz: "A - Z",
    bybenefits: "By Benefit",
    gummies: "Gummies",
    BestSellers: "Best Sellers",
    bundleandsave: "Bundle & Save",
    subscribeandsave: "Subscribe & Save",
    NewProducts: "New Products",
    ViewAll: "View All",
    acidophilous: "Acidophilus Supplements",
    adultgummies: "Adult Gummy Vitamins",
    advancemulties: "Multivitamins",
    Ashwagandha: "Ashwagandha Supplements",
    bvitamins: "B Vitamins Supplements",
    bcomplex: "B-Complex Supplements",
    berberinesupplements: "Berberine Phytosome Supplements",
    biotin: "Biotin Supplements",
    bundles: "Value Packs",
    cvitamins: "Vitamin C Supplements",
    valeriansupplements: "Valerian Root Supplements",
    calcium: "Calcium Supplements",
    cholestoff: "CholestOff Supplements",
    choline: "Choline Supplements",
    collagen: "Collagen Supplements",
    coQ10: "CoQ10 Supplements",
    cranberry: "Cranberry Supplements",
    dvitamins: "Vitamin D Supplements",
    diabeteshealthpack: "Daily Diabetes Health Pack",
    evitamins: "Vitamin E Supplements",
    elderberry: "Elderberry Supplements",
    fiber: "Fiber Supplements",
    fishoilomega: "Fish Oil & Omega-3 Supplements",
    flaxseedoil: "Flaxseed Oil Supplements",
    folicAcid: "Folic Acid Supplements",
    ginseng: "Ginseng Supplements",
    glucosaminechondroitincomplexwithMSMtriplestrengthvitaminD3:
      "Glucosamine Chondroitin Complex with MSM Triple Strength‡ + Vitamin D3",
    glpNutritionSupport:"Meet Your GLP-1 Ally",
    htp: "5-HTP Supplements",
    vitamind3k2: "Vitamin D3 + K2",
    hairSkinNails: "Supplements for Hair, Skin & Nails",
    herbs: "Herbal Supplements",
    iron: "Iron Supplements",
    kvitamins: "Vitamin K2 Supplements",
    kidsfirstgummies: "Kids Gummy Vitamins",
    kidsmultivitamins: "Kids Multivitamins",
    lysine: "L-Lysine Supplements",
    theanine: "L-Theanine Supplements",
    lutein: "Lutein Supplements",
    magnesium: "Magnesium Supplements",
    melatonin: "Melatonin Supplements",
    mensmultivitamins: "Men’s Multivitamins",
    minerals: "Mineral Supplement",
    multiomega: "Multi Omega 3",
    multivitamins: "Multivitamins",
    multisAdvanced: "Multivitamins",
    omega3supplements: "Omega-3 Supplements",
    tripleomegasupplements: "Triple Omega Supplements",
    potassium: "Potassium Supplements",
    prebiotics: "Prebiotic Supplements",
    prenatalandPostnatal: "Prenatal & Postnatal Supplements",
    probiotics: "Probiotic Supplements",
    samE: "SAM-e Supplements",
    supplements: "Supplements",
    tripleFlex: "Triple Flex",
    tripleOmega: "Triple Omega Supplements",
    turmericCurcumin: "Turmeric Curcumin Supplements",
    valerianroot: "Valerian Root Supplements",
    vitaminB: "B Vitamins Supplements",
    vitaminC: "Vitamin C Supplements",
    vitaminD: "Vitamin D Supplements",
    vitaminE: "Vitamin E Supplements",
    vitaminK: "Vitamin K2 Supplements",
    wellblends: "Nature Made® Wellblends™ Supplements",
    womensmultivitamins: "Women’s Multivitamins",
    zinc: "Zinc Supplements",
    zerosugargummies: "Zero Sugar‡ Gummies",

    bestSellerBadgeTxt1: "Vitamin D3 2000 IU (50 mcg) Softgels",
    bestSellerBadgeTxt: "BEST SELLER",
    newBadgeTxt: "NEW",
    bestSellers: "Best Sellers",
    bundelstitle: "Value Packs",
    whatdoineed: "What Do I Need?",
    askourexperts: "Ask Our Experts",
    research: "Research",
    TheDaily4: "The Daily 4™",
    emailmeavailabletitle:
      "We'll notify you when this product is back in stock. We don't share your address with anybody else.",
    shopall: "Shop All Vitamins & Supplements",
    exploremore: "Explore More",
    prebioticsHeading: "Prebiotic Supplements for Digestive & Gut Health",
    glucosamineChondroitin: "Glucosamine Chondroitin Complex with MSM Caplets",
    glucosamineChondroitin1: "Glucosamine Chondroitin Complex with MSM",
    giveadvanced: "Give your immune system a head start†",
    quickstart: "Quick Start Recommendations",
    vitaminheading: "Vitamins 101",
    vitamE: "Vitamin E",
    frstArticleDetialsPgTtl:
      "11 Sleeping Tips for Night Shift Workers to Get Quality Sleep",
    equelleBrandName: "Accept Cookies"
  },

  productNames: {
    vitaminC500mgwithRoseHips: "Multivitamin For Her + Omega-3 Gummies",
    multivitaminOmegaForHim: "Multivitamin + Omega-3 For Him Gummies",
    vitD32000IUSoftgels: "Vitamin D3 2000 IU (50 Mcg) Softgels",
    vitD35000IUFastDslvTblts: "Vitamin D3 5000 IU (125 mcg) Fast Dissolve Tablets",
    vitaminCExtraStrength500Mg: "Vitamin C Extra Strength 500 mg Gummies",
    elderberry: "Elderberry",
    vitamind3: "Vitamin D3",
    womensWellnessTxt: "Women’S Wellness + Bone Support With Vitamin D Bundle",
    bestSellerproduct: "Zinc 30 mg Tablets",
    vitamin500tablets: "Vitamin C 500 mg Tablets",
    biotinextrastrength: "Biotin Extra Strength 2500 mcg Softgels",
    hairskingummies: "Hair-Skin-Nails‡ Gummies",
    hairskinsoftgels: "Hair-Skin-Nails‡ 2500 mcg Softgels",
    mgmelatoninextrastrength: "5 mg Melatonin Extra Strength Gummies",
    multiOmega3ForHimGummiesTxt: "Multi + Omega 3 For Him Gummies",
    zerosugarmelatoningummies: "Zero Sugar‡ Melatonin Extra Strength 5 Mg Gummies",
    newproducts: "Wellblends™ Sleep Longer®",
    mgmelatoningummies: "10 mg Melatonin Gummies",
    womensMultivitmnSoftgels: "Women's Multivitamin 50+ Softgels",
    vitaminmaximumstrength: "Vitamin D3 Maximum Strength 10,000 IU (250 mcg)",
    prenatalmultivitaminsoftgels: "Prenatal Multivitamin + 200 mg DHA Softgels",
    prenatalmultivitaminfolicdhasoftgrls: "Prenatal Multivitamin Folic Acid + DHA Softgels",
    ashwagandhaTxt: "Ashwagandha 300 mg Gummies",
    relevantbiotinproduct: "3000 mcg Biotin Gummies for Hair, Skin & Nails (QA)",
    fiveHTP100mgChewableTablesTxt: "5-HTP 100 mg Chewable Tablets",
    multivitaminGummiesTxt: "Multivitamin Gummies",
    womensMultivitaminTabTxt: "Women's Multivitamin Tablets",
    womenMultivitaminSftgels: "Women's Multivitamin Softgels",
    womenswellnesspack: "Women's Wellness Support Value Pack",
    multisoftgels: "1 × Multi For Her Softgels",
    magnesiumProduct: "Magnesium L-Threonate with Vitamins C & D3",
    vitamind32000iutxt: "Vitamin D3 2000 IU (50 mcg) Gummies",
    cartmultisoftgels: "Multi For Her Softgels",
    womenMultivitaminfiftySftgels: "Women's Multivitamin 50+ Softgels",
    diabetesHealthPacketTxt: "Diabetes Health Pack† Packets",
    womensMultivit50Tablets: "Women'S Multivitamin 50+ Tablets",
    fivemgMelatoningummiesTxt: "5 mg Melatonin Gummies",
    tenmgMelatoninGummiestxt: "10 mg Melatonin Gummies",
    melatoningummiesmaximumstrength: "10 Mg Melatonin Gummies Maximum Strength Dosage‡",
    nurishByNatureMadeEveryGlamPackTxt: "Nurish By Nature Made® Everyday Glam™ Pack",
    calcium500MgWithVitD3TabltsTxt: "Calcium 500 mg with Vitamin D3 Tablets",
    wellblendsElderberryImmuneCaseTxt: "Wellblends™ Elderberry with Immune Care™",
    megnesiumExtraStrengthTxt: "Magnesium Extra Strength 400 mg Softgels",
    acidophilusprobiotictablets: "Acidophilus Probiotics Tablets",
    relevantbiotinproduct2: "Biotin Maximum Strength‡ 5000 mcg Softgels",
    biotin1000mcgsoftgels: "Biotin 1000 mcg Softgels",
    collagenpeptideppowder: "Collagen Peptides Powder",
    vitamincrosehips: "Vitamin C 500 mg Time Release with Rose Hips Tablets",
    vitamincrosehips1: "Vitamin C 500 mg with Rose Hips",
    vitamincplusrosehips: "Vitamin C + Rose Hips",
    vitaminCcaplets: "Vitamin C 500 mg Caplets with Rose Hips",
    glucosaminemcm: "Glucosamine Chondroitin Complex with MSM",
    newBadgeText: "NEW",
    vitamin: "Vitamin",
    vitaminC: "Vitamin C",
    multiVitaminPlusOmegaGummiesTxt: "Multivitamin + Omega-3 Gummies",
    writeAReviewLinkTxt: "Write a review",
    mensMultivitaminTabltTxt: "Men'S Multivitamin Tablets",
    mensWellnessRelaxBundleTxt: "Men’S Wellness + Relax Bundle†",
    glucosaminechondroitincomplexwithMSMtriplestrengthvitaminD3:
      "Glucosamine Chondroitin Complex with MSM Triple Strength‡ + Vitamin D3",
    vitD3PlusK2Softgels: "Vitamin D3 + K2",
    vitaminD3K2gummies: "Vitamin D3 K2 Gummies",
    vitD3PlusK2Softgels1: "Vitamin K2 100 mcg Softgels",
    maximumStrengthBiotin: "Maximum Strength Biotin 5000 mcg Softgels (QA)",
    maximumStrengthBiotin1: "3000 mcg Biotin Gummies for Hair, Skin & Nails (QA)",
    collagenPeptidesPowder: "Collagen Peptides Powder",
    hairSkinAndNailWithBiotin: "Hair Skin and Nails with Biotin 2500 mcg Softgels",
    extraStrengthBiotin: "Extra Strength Biotin 2500 mcg Softgels",
    hairSkinandNailswithBiotin2500mcgGummies:
      "Hair Skin and Nails with Biotin 2500 mcg Gummies",
    extraStrengthVitC1000mcg: "Extra Strength Vitamnin C 1000 mg Tablets",
    magnesiumLThreonate: "Magnesium L-Threonate",
    multivitaminforHerTablts: "Multivitamin For Her Tablets",
    womensbonesupport: "Women’s Wellness + Bone Support with Vitamin D Value Pack",
    vitaminb12: "Vitamin B12",
    algaeOmega: "Algae Omega-3",
    testProduct: "TEST PRODUCT SHORT TITLE",
    kidsFrsrFibrGummies: "Kids First Fiber Gummies",
    multiGummies: "Multivitamin Gummies",
    superBComplex: "magnesium",
    superBComplexWithVitCAndFolicAcidTblt:
      "Super B Complex with Vitamin C and Folic Acid Tablets"
  },

  productDetailsPage: {
    showMoreTxt: "VIEW MORE\nPRODUCT DESCRIPTION",
    showLesstxt: "VIEW MORE",
    pack: "PACK",
    breadCurmb1: "Home",
    ingredients: "Ingredients",
    nutrientshortfall: "Nutrient Shortfalls",
    quantity: "Quantity",
    countTxt: "Count:",
    count: "90",
    pdpprice: "$20.99",
    bottlecount1: "60",
    filterDialog: "Filter\nClear All",
    fAQSubTitle: "See our frequently asked questions below:",

    secondAnswers:
      "We recommend that you follow the suggested dosage found on each bottle (one softgel per day). However, as with all supplement regimens and especially during pregnancy, you should consult with your healthcare professional before starting any supplement routine.",

    fourthAnswers:
      "Most Nature Made® products are gluten free. Please refer to the label of the bottle or packaging that it is contained in. If you have any additional questions, please call us and we'll be happy to assist you.",

    ourProductsTxt: "Our Products",
    zincmgTablets: "Zinc 30 mg Tablets - 100",

    qualitySupplemntHeading:
      "If it’s USP Verified, you can trust that what’s on the label is what’s in the bottle.",

    delivryEveryDays30: "Delivery every 30 Days",
    delivryEveryDays45: "Delivery every 45 Days",
    delivryEveryDays60: "Delivery every 60 Days",
    delivryEveryDays90: "Delivery every 90 Days",
    save10PercntPlusFreeShipng: "Save 10% + Free Shipping",
    pauseOrCncel: "Pause or Cancel Anytime",

    fBookTxt: "Facebook",
    twittrLoginTxt: "Want to log in first?",
    pintrestSignInTx: "Sign in to save this Pin!",

    thisProdHasNoLongerMsg:
      "This product has been discontinued and is no longer available.",

    breadCurmb2: "Multivitamins",
    coupanCodeDoNotAplyTxt: "Coupon codes do not apply to bundles",
    bundlePrice: "$64.54 ($80.67 value)",
    bundlePrice1: "$64.54",
    bundleCompPrice: "($80.67 value)",

    Softgel: "SOFTGEL",
    bundlesViewMore:
      "VIEW MORE\nread more about What are Nature Made® Value Packs?",

    productsprice1: "$14.69",
    gummies: "GUMMIES",
    strengthTxt: "MEN'S HEALTH",
    stressTxt: "GENERAL WELLNESS",
    servingSize: "Serving size: 3 gummies",
    servingSize1: "SERVING SIZE: 1 TABLET",

    youHaveEarnedFreeShpng: "$5.01 away from Free Shipping",
    youHaveEarnedFreeGift: "$15.01 away from a Free Gift",

    youMayAlsoLike: "YOU MAY ALSO LIKE",
    advancedGummiesHim: "Advanced Multivitamin Gummies For Him",
    writeareview: "Write a review",
    ratingcount: "(0)",

    productsprice: "$13.59",
    exploremoreheading: "Explore More",

    productdescription:
      "Get 60% more total nutrients◆ in your multivitamin gummies including a good source of Magnesium and Calcium an excellent source of all 8 B Vitamins! Specially formulated for adults to get the nutritional support you need in three daily gummies.†",

    bottlecount: "90",
    shopNowTxt: "Shop Now",

    bundleDescription1:
      "Nature Made® Burp-Less♦ Ultra Omega-3†† from Fish Oil helps support a healthy heart, brain, and eyes. This high quality Omega-3 fish oil supplement provides 1400 mg (1000 mg Omega-3††) in only 1 daily softgel that is purified to remove mercury and other contaminants.▲ Supportive but not conclusive research shows that consumption of EPA and DHA omega-3 fatty acids may reduce the risk of coronary heart disease. (See nutrition information for total fat and cholesterol content).†",

    bundleDescription2:
      "A healthy cholesterol level is an important part of heart health. Reducol® works to help lower dietary cholesterol by reducing the absorption of dietary cholesterol into the bloodstream.‡ Products containing at least 400 mg per serving of plant sterols and stanols, eaten twice a day with meals for a daily intake of at least 800 mg as part of a diet low in saturated fat and cholesterol, may reduce the risk of heart disease. One serving of Nature Made® CholestOff Plus® supplies 900 mg of plant sterols and stanols for a daily intake of 1800 mg.",

    bundleDescription3:
      "CoQ10 is found in most cells in the human body. In fact, it plays a vital role inside the part of the cell that’s responsible for energy production—the mitochondria. The hardest working cells in your body, including the cells in your heart, have the highest concentrations of mitochondria. Which is why precisely why CoQ10 is an important nutrient for heart function.†",

    itemnumber: "ITEM #HL000377",
    itemnumber1: "ITEM #2927",
    itemnumber2: "ITEM #4271",
    itemnumber3: "ITEM #2546Z",
    itemnumber4: "ITEM #2917",

    labelquantity: "1",
    onetimepurchase: "One-time purchase",

    productprice: "$19.99",
    bottlecountprice: "$12.49",
    bottlecountprice1: "$19.29",
    bottlecountprice2: "$10.00",

    subscribedPrice: "$26.62",
    bottlecountprice3: "$14.79",
    bottlecountprice4: "$26.44",

    cartprice: "$24.38",
    cartprice1: "$12.19",
    cartprice2: "$149.97",

    addtocart: "ADD TO CART",
    benefits: "Benefits",
    productreviews: "Reviews",

    quantitymessage: "Order limit is 3 of the same product",
    itemaddtocart: "Item added to your cart",
    cartquantity: "1",

    questions: "Questions?\nVIEW ALL FAQ\nVIEW ALL FAQ ON QUESTIONS?",

    uspverifiedheading:
      "If it’s USP Verified, you can trust that what’s on the label is what’s in the bottle.",

    howtoreadsupplementlabel: "HOW TO READ A SUPPLEMENT LABEL",
    freegiftmsg: "You have earned a Free Gift",
    soldout: "SOLD OUT",
    emailmeavailable: "Email Me When Available",

    bundlefree: "THIS BUNDLE SHIPS FREE",
    onlineonly: "ONLINE ONLY"
  },

  healthNeedsdata: {
    beauty: "Beauty Supplements",
    bonehealth: "Bone Supplements",
    brainhealth: "Brain Health Supplements",
    digestion: "Digestion Supplements",
    energy: "Energy Supplements",
    b12: "B12",
    eyehealth: "Eye Health Supplements",
    wellness: "General Wellness Supplements",
    heart: "Heart Supplements",
    healthAging:"Healthy Aging Supplements",
    immunehealth: "Immune Support Supplements",
    immuneHealthinDev: "Immune Health Supplements",
    joints: "Joints Supplements",
    kids: "Kids Gummy Vitamins",
    menhealth: "Men's Health Supplements",
    mood: "Mood Supplements",
    prenatalAndPostnatalTxt: "Prenatal & Postnatal Supplements",
    sleep: "Sleep Supplements",
    stress: "Stress Supplements",
    womenshealth: "Women's Health Supplements",
    advancemultivitamin: "Advanced Multivitamin",
    berberinephystome: "Berberine Phytosome",
    immmunesupport: "Immune & Superfood™",
    gutHealth: "Gut Health Supplements for Digestion Support†",
    gutarticles: "Gut Health Articles",
    gutHealthAndDigestion: "Supplements for Gut Health & Digestion Support†",
    bundlesDescription: "A Nature Made® value pack is a pack of vitamins and supplements for different needs. Each value pack contains Nature Made® supplements offered at a discount when purchased together.†"
  },

  heading: {
    marketingSubsPgHeading: "Make wellness your new routine",
    RelatedArticles: "Related Articles",
    collection: "COLLECTIONS",
    relatedCollections: "RELATED COLLECTIONS",
    otherpeoplebuying: "OTHER PEOPLE ARE BUYING",
    waysToThriveHeading: "Ways to Thrive Today",
    energyresource: "Energy Resources",
    bVitaminsResources: "B Vitamins Resources",
    continueReadingTxt: "CONTINUE READING",
    waysToTriveArticle1: "Miso Peach Oatmeal",
    waysToTriveArticle2: "Seed Crackers & Broccolini Dip",
    waysToTriveArticle3: "Coconut Butter Dates with Pistachios",
    waysToTriveArticle4: "Can You Take Vitamin D and B12 Together?",
    article4: "Can You Take Vitamin D and B12 Together?",
    article5: "Tips for How to Take Your Vitamins",
    subscriptionTitle: "Helpful content to support your practice",
    faqQuestion1: "What does omega-3 from fish oil help with?",
    sortby: "Sort By:Featured",
    caplet: "Caplet",
    gummy: "Gummy",
    tablet: "Tablet",
    firstcount: "0 - 30",
    secondcount: "30 - 45",
    thirdcount: "45 - 60",
    fourthcount: "60 - 90",
    fifthcount: "90+"
  },

  searchbar: {
    womenshealth: "Women's Health",
    vitamins: "vitamins",
    biotin: "biotin",
    beauty: "beauty",
    presuggestedSearch1: "Women's Health",
    presuggestedSearch2: "Men's Health",
    subHeader: "Search Results for",
    validationMsg: 'No products found for "hijklms"',
    validationMsg1: 'No products found for "23413"',
    validationMsg2: 'No products found for "!@#$"',
    validationMsg3: 'No products found for "asdfgh12345"',
    searchResultTab1: "Products (116)",
    productTab: "Products (3)",
    resourceArticleTab: "Resources and Articles (6)",
    searchResultTab2: "Product Lines (6)",
    searchResultTab3: "Resources and Articles (270)",
    searchresultTab4: "Information (2)",
    collections: "COLLECTIONS",
    articles: "ARTICLES",
    information: "INFORMATION",
    searchValidMessage: "Sorry we could not find any results",
    searchtips: "Search Tips",
    recentlybviewed: "RECENTLY VIEWED",
    suggestedsearch: "Suggested Searches",
    healthbyExperts: "Health Articles Written by Our Experts"
  },

  searchDropdown:{
    startYourRoutine:"Start Your Routine",
    gummies:"Gummies",
    whatShouldITake:"What Should I Take?",
    mensHealth:"Men's Health",
    womensHealth:"Women's Health",
    multivitamins:"Multivitamins",
    bestSellers:"Best Sellers",
    coupons:"Coupons",
    health:"Health",
    whereToStart:"Where To Start"
  },

  values: {
    onetimepurchase: "$19.99",
    subscribeprice: "$17.99",
    onetimepurchaseprice1: "$19.29",
    subscribedprice1: "$17.36",
    oneTimePurchase: "$14.69",
    subscribeAndSave: "$26.44",
    subscribeAndSave2: "$19.79",
    oneTimePurchase1: "$21.99",
    oneTimePurchase2: "$14.19",
    oneTimePurchase3: "$23.59",
    subscribeAndSave1: "$25.54",
    subscribeAndSave3: "$21.23"
  },

  productTitles: {
    productNameClr: "Women's Multivitamin Tablets",
    multivitaminWthIron: "Multivitamin Tablets with Iron",
    healthAricleTitle: "Health Articles",
    womendescription: "No two women are the same and needs are always changing, yet every woman can benefit from some care and attention to daily nutritional needs as well as their immune, heart and bone health plus healthy hair, skin & nails. Some key nutrients for women include Folic Acid, Vitamin B12, Calcium, Vitamin C, and Iron. So whether you’ve entered a new life stage or just want some TLC, we have supplements that support you from the inside out.†",
    mendescription: "Men have unique needs, too, that can vary depending on age and lifestyle. In addition to daily nutritional support, men’s wellness needs include supporting immune, muscle and heart health, and cellular energy metabolism. On top of a daily multivitamin, important nutrients for men include Vitamin D, Magnesium and Omega-3 fatty acids. We’ve got all that and more in a variety of supplements ready to be added to your daily regimen so that you don’t miss a beat.†",
    expandDescription: "We get it, life gets busy. We might not always stop to think about our wellness. How can we ensure we’re getting enough of the essential nutrients we need from our food? What if sometimes our wellbeing needs a little extra support? Supplementing with vitamins, minerals and other nutrients can help support your nutritional needs so that you can focus on everything else.†",
    HighAbsorptionMagnesiumGlycinate: "High Absorption Magnesium Glycinate Capsules 200 mg",
    ValerianRoot: "Valerian Root 200 mg Capsules",
    vitaminRoseHiptablet: "Vitamin C 500 mg Time Release with Rose Hips Tablets",
    vitamind3softgels: "Vitamin D3 + K2 Softgels",
    vitamind3Gummies: "Vitamin D3 K2 Gummies",
    articles: "Articles",
    dailyPack: "The Daily 4™ Value Pack",
    advancedMultivitamin: "Advanced Multivitamin",
    featuredArticles: "Featured Articles",
    womensMultivitaminTablet: "Women's Multivitamin 50+ Softgels",
    advancedMultivitaminForHer: "Advanced Multivitamin Gummies For Her",
    advancegummiesforadult: "Advanced Multivitamin For Adults Gummies",
    berberinecapsule: "Better Absorption‡ Berberine Phytosome 550 mg Capsules",
    melatoningummies: "Nature Made® Melatonin Time Release 3 mg Gummies",
    melatoninGummies: "Melatonin Time Release 3 mg Gummies",
    skinHydrationGummies: "Skin Hydration + Ceramides Gummies",
    vitaminfaqanswer: "Vitamin B12 is an essential B vitamin that supports cellular energy production, brain cell function, and the production of neurotransmitters important for mood health. It also helps reduce fatigue for those with low Vitamin B12 levels.†",
    ultraOmegafromFishOil: "Ultra Omega-3†† from Fish Oil 1400 mg Softgels, Burp-Less♦",
    vitD32000IUPerGummies: "Vitamin D3 2000 IU (50 mcg) per serving Gummies",
    creatineMonohydrate: "Creatine Monohydrate 5 g Drink Mix Powder",
    elderberrywithVitaminCandZincGummies: "Elderberry with Vitamin C and Zinc Gummies",
    advancedmultivitaminGummiesforher: "Advanced Multivitamin Gummies For Her with Magnesium",
    multivitaminForHer: "Multivitamin For Her Tablets",
    multivitaminForHer50PlusTblet: "Multivitamin For Her 50+ Tablets with No Iron",
    magnesiumGlycinate200mg: "Magnesium Glycinate 200 mg per serving Capsules"
  },

  productsGeneralPgTitles: {
    productGenerlTitle: "Product & General Questions",
    generalquestion: "General Questions",
    allArticlesTxt: "All articles",
    trendingTopicsTxt: "Trending Topics",
    ingredntAndAllrgensTxt: "Ingredients & Allergens",
    reportIssuesTxt: "Report Issues",
    ordersTxt: "Orders",
    billingAndShippingTxt: "Billing & Shipping",
    accountInfrmtnTxt: "Account Information",
    subscriptionTxt: "Subscriptions",
    refundAndReturnsTxt: "Refund & Returns",
    promoCodeAndCoupanTxt: "Promo Codes & Coupons",
    ourCompanyTxt: "Our Company",
    understandingSuplmntLablsTxt: "Understanding Supplement Labels",
    magnesiumTxt: "Magnesium",
    advancedmultigummies: "Advanced Multi Gummies",
    picklemultigummies: "Pickle Flavored Multi Gummies",
    picklemerchandise: "Pickleball Merchandise",
    MagAnswer2: "For more information about the different types of Magnesium and their benefits, please read our health article:",
    vitDTxt: "Vitamin D",
    fishOilTxt: "Fish Oil",
    melatoninTxt: "Melatonin",
    dailyfourtm: "The Daily 4",
    searchterm: "trendingg",
    searchResults: '33 Results For "Trendingg"',
    yesTxt: "Yes",
    noTxt: "No",
    wasThisArticleHelpTxt: "Was this article helpful?"
  },

  aboutusdData: {
    about: "About Nature Made",
    history: "Our History",
    experts: "Our Experts",
    quality: "Quality That Counts",
    brands: "Our Brands",
    helpUs: "How can we help you today?",
    helpcontactUs: "What can we help you with?",
    affiliate: "Partner with Nature Made Today!",
    cookiesheading: "Your Choices Regarding Cookies",
    healthcareprofessional: "Support your patients",
    meetourexpert: "Meet Our Experts",
    accessibilityOnNM: "Accessibility on Naturemade.com"
  },

  filterBtn: {
    filter: "Filter by",
    clearAllTxt: "Clear All ",
    filterTitle: "Filter"
  },











};